function params = delta_params()

Rb = 0.0610;
Rp = 0.0440;
L1 = 0.0800;
L2 = 0.1557;

% Hardware/user convention:
%   command 0 deg is the old/model 90 deg arm pose.
%   positive command motion is flipped, so +80 deg maps to model 10 deg.
command_zero_model_deg = 90;
command_direction = -1;
command_min_deg = 0;
command_max_deg = 80;
home_command_deg = 0;

home_theta_model_deg = command_zero_model_deg + command_direction * home_command_deg;
model_limit_deg = command_zero_model_deg + command_direction * [command_min_deg, command_max_deg];
th_min = deg2rad(min(model_limit_deg));
th_max = deg2rad(max(model_limit_deg));

% Default home pose: command theta = [0 0 0] deg, model theta = [90 90 90] deg.
home_theta_model_rad = deg2rad(home_theta_model_deg);
r_home = Rb - Rp + L1*cos(home_theta_model_rad);
z_home = -L1*sin(home_theta_model_rad) - sqrt(max(L2^2 - r_home^2, 0));

params = struct( ...
    'Rb', Rb, ...
    'Rp', Rp, ...
    'L1', L1, ...
    'L2', L2, ...
    'phi', [0, 2*pi/3, 4*pi/3], ...
    'th_min', th_min, ...
    'th_max', th_max, ...
    'command_zero_model_deg', command_zero_model_deg, ...
    'command_direction', command_direction, ...
    'command_min_deg', command_min_deg, ...
    'command_max_deg', command_max_deg, ...
    'home_command_deg', home_command_deg, ...
    'home_theta_model_deg', home_theta_model_deg, ...
    'ws_lim', [ -0.20, 0.20; ...
                -0.20, 0.20; ...
                -0.30, 0.00 ], ...
    'home_pos', [0; 0; z_home], ...
    'f_base', sqrt(3)*Rb, ...
    'e_platform', sqrt(3)*Rp ...
    );
end
